### PR TITLE
Allow getting executable path

### PR DESCRIPTION
**Pull request by derkan**
Allow getting executable path with daemon.ExecPath()

### CODE REVIEW

**Comment by takama** [comment]
Hi

Thank you for your pull request.
Why we need do that? Any reason?

thanks

**Comment by derkan** [comment]
Hi,
When run as daemon, `ExecPath`, returns the absolute path to the currently executable which is needed also by program to get paths referential to exe path(for example getting conf dir which lives in same dir as exe.

To see how it differs from OS to OS, check `execPath` functions for `linux`, `windows` and `freebsd`. It will be a good idea to export it with name `ExecPath`.

**Comment by takama** [comment]
Ok, let me explain some thoughts about config files. I think, config file should not be in the directory which binary is living, due to difficulties to find it with 100% guarantee. But it is my own opinion.
What about your improvement. If we will export it in this way, we should guarantee existence of realisation of it - `execPath`. Please look also `executablePath` in` helper.go` and how it's used in implementations. It was used as first iteration in looking of executable path. Maybe implementation of it  should be more transparent?

**Comment by derkan** [comment]
`executablePath` assumes that service name and exe name are same. But this is not always true. 

For example  I'm running same exe with different params, so I installed different services with different names(pls also check my answer to #37 for creating services with params).

Please also check this [project](https://github.com/VividCortex/godaemon) which also exports this function(`GetExecutablePath`) with same intensions.

**Comment by takama** [comment]
Correct me if I'm wrong, `executablePath` assumes exactly what in args. If we will use os.Args, it hold the command-line arguments, starting with the program name.

**Comment by derkan** [comment]
OK. if `name` param is sent a blank string while calling `executablePath` we'll get the same answer for `ExecPath`. If we can make  `executablePath` exportable(i.e. rename to `ExecutablePath`) than no need for my pull request. (It needs renaming in 6 files.)

**Comment by takama** [comment]
I'm just asking for your advice. This discussion is not pressure :)

**Comment by derkan** [comment]
:-) os.Args is not realiable on all systems if we are running our exe as a service because may It return executable of service subsystem(as it starts our exe)?

**Comment by derkan** [comment]
Also for past message about pull request, please do not take as a complaint. I wanted to say that renaming of function can be alternative way to access `execPath`.

**Comment by takama** [comment]
Yes, exactly, it may be subsystem. Do you think, we should remove `executablePath` method?

**Comment by derkan** [comment]
I think it should remain, its needed when we are installing/starting/stopping/uninstalling service(with custom service name) and works without a problem.

**Comment by takama** [comment]
I care about results. What we should have as results? Exportable ExecPath and orphaned executablePath?

**Comment by derkan** [comment]
I think we should think `executablePath` as internal function which is called while installing/starting/stopping/uninstalling service, while `ExecPath` is called during runtime of exe.

**Comment by takama** [comment]
ok, accepted.

**Comment by derkan** [comment]
thanks :-)

**Pull request merged**
